version: '3.7'
services:
  zoo1:
    # from https://github.com/simplesteph/kafka-stack-docker-compose/blob/master/zk-single-kafka-single.yml
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./zk-single-kafka-single/zoo1/data:/data
      - ./zk-single-kafka-single/zoo1/datalog:/datalog
  kafka1: 
    # from https://github.com/simplesteph/kafka-stack-docker-compose/blob/master/zk-single-kafka-single.yml
    image: confluentinc/cp-kafka:5.4.0
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1
  kafdrop:
    image: obsidiandynamics/kafdrop
    hostname: kafdrop
    environment:
      KAFKA_BROKERCONNECT: ${DOCKER_HOST_IP:-127.0.0.1}:9092
    ports:
      - "9000:9000"
  kafka-producer:
    build:
      context: ./test-kafka-producer
      dockerfile: src/main/docker/Dockerfile.jvm
    hostname: kafka-producer
    image: test-kafka-producer
    environment:
      KAFKA_SERVERS: ${DOCKER_HOST_IP:-127.0.0.1}:9092
    depends_on:
      - kafka1
  # Note: a hostname must not be defined in order to create replicas with different hostnames
  kafka-consumer:
    build:
      context: ./test-kafka-consumer
      dockerfile: src/main/docker/Dockerfile.jvm
    image: test-kafka-consumer
    environment:
      KAFKA_SERVERS: ${DOCKER_HOST_IP:-127.0.0.1}:9092
    ports:
      - "8080:8080"
    depends_on:
      - kafka1
